#######################
# Configuration Shell #
#######################

shell.executable("/bin/bash")

# Config file and useful variables loading
configfile : "config.json"
ref_dir = config["ref_dir"]
DATA = config["data_path"]
Results = config["results_path"]
chromomap = config["chromomap"]
scriptdir = config["scriptdir"]
genome = config["genome_ref"]
missing_data = config["missing_data_accepted_for_SNP"]
min_allele = config["min_alleles_for_SNP"]
max_allele = config["max_alleles_for_SNP"]
ploidy = config["species_ploidy"]
min_coverage = config["minimum_x_coverage"]
trimming = config["trimming"]
kmin = config["k_min"]
kmax = config["k_max"]
n_SNPs = config["nbr_of_selected_SNPs"]
gap_SNP = config["dist_min_betwin_2_SNPs"]
n_axes = config["nbr_axes_to_plot_for_PCA"]
fai = config["genome_ref.fai"]


# List of methods
METHOD = config["methods_thining"]

# List of samples
SAMPLES = [ind 
        for inds in config["species"].values()
        for ind in inds
]

# Trimming à faire ?
if trimming == "NO":
        trimming_outputs = [
                expand(f"{Results}/0-trimming/{{sample}}_R1.clean.fastq", sample=SAMPLES),
                expand(f"{Results}/0-trimming/{{sample}}_R2.clean.fastq", sample=SAMPLES)
        ]
        R1 = f"{Results}/0-trimming/{{sample}}_R1.clean.fastq"
        R2 = f"{Results}/0-trimming/{{sample}}_R2.clean.fastq"
else:
        trimming_outputs = []
        R1 = f"{DATA}/{{sample}}_R1.clean.fastq"
        R2 = f"{DATA}/{{sample}}_R2.clean.fastq"


# Target rules
rule all:
    input:
        # Trimming 
        trimming_outputs,
        
        # Alignment to the reference genome
        expand(f"{Results}/1-alignment/{{sample}}.bam",sample=SAMPLES),
        
        # Name-sorted BAM files required for the next step
        expand(f"{Results}/2-sorting/2.1-name/{{sample}}_name.bam",sample=SAMPLES),
        
        # Pair reads information correction
        expand(f"{Results}/2-sorting/2.2-fixmate/{{sample}}_fixmate.bam",sample=SAMPLES),
        
        # Coordinate-sorted BAM files for all other steps
        expand(f"{Results}/2-sorting/2.3-sorting/{{sample}}_sorted.bam",sample=SAMPLES),
        
        # Duplicats removal
        expand(f"{Results}/2-sorting/2.4-rdup/{{sample}}_rdup.bam",sample=SAMPLES),
        
        # List of BAM files for FreeBayes
        f"{Results}/2-sorting/2.5-list/all_indiv_bam_list.txt",
        
        # Variant calling with FreeBayes
        f"{Results}/3-SNP_calling/3.1-variants/all_indiv_variants.vcf",
        
        # Variant filtering : selection of bialelic SNPs which have not too much missing data
        f"{Results}/3-SNP_calling/3.2-SNP/all_indiv_SNP.vcf",

        # Informations on missing data about samples ans SNPs
        f"{Results}/3-SNP_calling/3.3-missing_data/missing_data_per_individual.imiss",
        f"{Results}/3-SNP_calling/3.3-missing_data/missing_data_per_SNP.lmiss",
        f"{Results}/3-SNP_calling/3.3-missing_data/plot_missing_data_per_SNP.png",

        # SNP table generation for the chromosome mapping 
        f"{chromomap}/all_indiv_SNP_table.txt",

        # IV - Thinning
        # List of unselected SNPs
        f"{Results}/4-thinning/4.1-raw_analyse/4.1.1-SNP_list/no_filtered_SNP_all_species.txt",

        # Distribution of distances between adjacent SNPs
        f"{Results}/4-thinning/4.1-raw_analyse/4.1.2-distance/all_SNP_dist_mat.txt",
        f"{Results}/4-thinning/4.1-raw_analyse/4.1.2-distance/all_SNP_dist_hist.png",

        # Number of SNPs per chromosome
        f"{Results}/4-thinning/4.1-raw_analyse/4.1.3-nbr_SNP/nbr_SNPs_chromosome_all_SNP.tsv",

        # Cumulative genomic positions of all SNPs for random and proportional methods of thinning 
        f"{Results}/4-thinning/cumulative_positions.txt",

        # SNP selection
        expand(f"{Results}/4-thinning/{{method}}/filtered_SNP_{{method}}.txt", method=METHOD),

        # Creating tables for visualisation with ChromoMap if you are interested
        expand(f"{chromomap}/{{method}}_filtered_SNP_table.txt", method=METHOD),

        # VCF indexing files
        expand(f"{Results}/4-thinning/{{method}}/index_trio.vcf.gz", method=METHOD),
        expand(f"{Results}/4-thinning/{{method}}/index_trio.vcf.gz.tbi", method=METHOD),

        # Filtered VCF files
        expand(f"{Results}/4-thinning/{{method}}/{{method}}_selected_snps.vcf", method=METHOD),


        # V - After-thinning analyses
        
        # ADMIXTURE
        # Files generation for chromosome renaming
        f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.1-chrom_list/chrom_list.txt",
        f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.1-chrom_list/chrom_correspondance.txt",
        # Chromosome renaming
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.2-vcf_anno_chrom/renamed_chr_{{method}}_SNP.vcf", method=METHOD),
        # Conversion of VCF files to BED files with PLINK
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.3-plink/renamed_chr_{{method}}_SNP.bed", method=METHOD),
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.3-plink/renamed_chr_{{method}}_SNP.bim", method=METHOD),
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.3-plink/renamed_chr_{{method}}_SNP.fam", method=METHOD),
        # ADMIXTURE output files
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.4-results/{{method}}_log{{k}}.out", k=range(kmin,(kmax+1)), method=METHOD),
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.4-results/renamed_chr_{{method}}_SNP.{{k}}.P", k=range(kmin,(kmax+1)), method=METHOD),
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.4-results/renamed_chr_{{method}}_SNP.{{k}}.Q", k=range(kmin,(kmax+1)), method=METHOD),
        # Cross-validation error files for all tested K values ansd plot
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.5-CV_error/{{method}}_renamed_chr_SNP.cv.error", method=METHOD),
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.5-CV_error/plot_{{method}}_renamed_chr_SNP_cv_error.png", method=METHOD),
        # ADMIXTURE plot for all tested K values
        expand(f"{Results}/5-after_thinning_analyse/5.1-ADMIXTURE/5.1.6-plot/{{method}}_admixture_plot_k{{k}}.png", k=range(kmin,(kmax+1)), method=METHOD),

        # PCA
        f"{Results}/5-after_thinning_analyse/5.2-ACP/5.2.1-species_list/presumed_species_information.txt",
        expand(f"{Results}/5-after_thinning_analyse/5.2-ACP/5.2.2-ACP_plot/{{method}}_ACP.done", method=METHOD),

        # Comparaison of thinning methods
        # Distance between adjacent SNPs
        # Distance matrix construction
        expand(f"{Results}/5-after_thinning_analyse/5.3-comparaison/5.3.1-file_generation/{{method}}_dist_mat.txt", method=METHOD),
        # Distance distibution histograms
        expand(f"{Results}/5-after_thinning_analyse/5.3-comparaison/5.3.2-histogramme_distance_SNPs/{{method}}_dist_hist.png", method=METHOD),

        # Comparaison of SNP counts per chromosome for each methods
        f"{Results}/5-after_thinning_analyse/5.3-comparaison/5.3.1-file_generation/nbr_SNPs_chromosome_methode.tsv"

# Import rules 
include: "rules.smk"
